controller_list:
  - name: fake_base_controller
    type: $(arg execution_type)
    joints:
      - motortom2m
      - joint2
      - joint4
      - joint6
  - name: fake_end_controller
    type: $(arg execution_type)
    joints:
      - end
initial:  # Define initial robot poses.
  - group: base
    pose: slm